[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.buildOnly]
command = "cargo"
args = ["build"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.install]
command = "mv"
args = ["config", "target/debug/config"]

[tasks.build]
dependencies = [
    "format",
    "buildOnly",
    "test"
]

[tasks.package]
dependencies = [
    "format",
    "clean",
    "buildOnly",
    "test",
    "install"
]

[tasks.watch]
command = "cargo"
args = ["watch", "-x", "run"]
dependencies = [
    "format",
    "buildOnly",
]