[package]
name = "copilot-config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { workspace = true }
copilot-utils = { path = "../copilot-utils" }
lazy_static = "1.4.0"
toml = "0.7.3"
